[tox]
envlist =
    py3{10,11,12,13,14}-django{4_2,5_0,5_1,5_2}
    py3{12,13,14}-django{6_0}

[testenv]
commands = pytest {posargs}
package = editable
deps =
	-r dev-requirements.txt
	Django~={env:DJANGO_VERSION}.0

passenv =
    DJANGO_VERSION
    PYTHON_VERSION

setenv =
    PYTHONPATH = {toxinidir}

    # Python versions:
    py310: PYTHON_VERSION=3.10
    py311: PYTHON_VERSION=3.11
    py312: PYTHON_VERSION=3.12
    py313: PYTHON_VERSION=3.13
    py314: PYTHON_VERSION=3.14

    # Django versions:
    django4_2: DJANGO_VERSION=4.2
    django5_0: DJANGO_VERSION=5.0
    django5_1: DJANGO_VERSION=5.1
    django5_2: DJANGO_VERSION=5.2
    django6_0: DJANGO_VERSION=6.0
